name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile
      - run: (cd client; yarn --frozen-lockfile)
      - run: (cd server; yarn --frozen-lockfile)
      - run: (cd client; yarn eslint .) && (cd server; yarn eslint .)
